import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { AnalysisListPage } from './AnalysisListPage'
const { apiRequest } = vi.hoisted(() => ({ apiRequest: vi.fn() })); vi.mock('../../api/client', () => ({ apiRequest }))
describe('AnalysisListPage', () => { beforeEach(() => apiRequest.mockImplementation((path?: string) => path === '/api/assets' ? Promise.resolve([{ id: 'a', name: '成绩' }]) : path === '/api/assets/a/preview' ? Promise.resolve({ rows: [{ name: '张三', score: 90 }] }) : Promise.resolve([])))
  afterEach(cleanup)
  it('选表后展示预览并提交自然语言需求创建分析', async () => { render(<MemoryRouter initialEntries={['/analyses']}><Routes><Route path="/analyses" element={<AnalysisListPage />} /></Routes></MemoryRouter>); await screen.findByText('历史分析'); fireEvent.click(screen.getByRole('checkbox')); expect(await screen.findByText('张三')).toBeInTheDocument(); expect(apiRequest).toHaveBeenCalledWith('/api/assets/a/preview'); fireEvent.change(screen.getByLabelText('分析需求'), { target: { value: '按姓名展示成绩' } }); fireEvent.click(screen.getByRole('button', { name: '创建分析' })); expect(apiRequest).toHaveBeenCalledWith('/api/analyses', expect.objectContaining({ method: 'POST' })) }) })
  it('应用失败诊断建议到需求输入框但不自动重试', async () => { apiRequest.mockImplementation((path?: string, init?: RequestInit) => path === '/api/assets' ? Promise.resolve([{ id: 'a', name: '成绩' }]) : path === '/api/assets/a/preview' ? Promise.resolve({ rows: [{ name: '张三', score: 90 }] }) : path === '/api/analyses' && init?.method === 'POST' ? Promise.reject({ payload: { guidance: { summary: '字段不匹配', suggestion: '改用成绩字段', revisedRequirement: '按姓名展示成绩' } } }) : Promise.resolve([])); render(<MemoryRouter><AnalysisListPage /></MemoryRouter>); await screen.findByText('历史分析'); fireEvent.click(screen.getByRole('checkbox')); fireEvent.change(screen.getByLabelText('分析需求'), { target: { value: '原始需求' } }); fireEvent.click(screen.getByRole('button', { name: '创建分析' })); expect(await screen.findByText('字段不匹配')).toBeInTheDocument(); const callCountBeforeApply = apiRequest.mock.calls.length; fireEvent.click(screen.getByRole('button', { name: '应用建议' })); expect(screen.getByLabelText('分析需求')).toHaveValue('按姓名展示成绩'); expect(apiRequest).toHaveBeenCalledTimes(callCountBeforeApply) })
