import { useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { apiRequest, type AnalysisSummary, type DataAsset, type DataAssetPreview } from '../../api/client'
export function AnalysisListPage() { const [items, setItems] = useState<AnalysisSummary[]>([]); const [assets, setAssets] = useState<DataAsset[]>([]); const [selected, setSelected] = useState<string[]>([]); const [previews, setPreviews] = useState<Record<string, DataAssetPreview | null>>({}); const [primaryAssetId, setPrimaryAssetId] = useState(''); const [requirement, setRequirement] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = () => Promise.all([apiRequest<AnalysisSummary[]>('/api/analyses'), apiRequest<DataAsset[]>('/api/assets')]).then(([history, tables]) => { setItems(history); setAssets(tables) }).catch(() => setError('分析历史加载失败。'))
  useEffect(() => { load() }, [])
  useEffect(() => { selected.filter((id) => !(id in previews)).forEach((id) => { setPreviews((current) => ({ ...current, [id]: null })); apiRequest<DataAssetPreview>(`/api/assets/${id}/preview`).then((preview) => setPreviews((current) => ({ ...current, [id]: preview }))).catch(() => setPreviews((current) => ({ ...current, [id]: { rowCount: 0, rows: [] } }))) }) }, [selected, previews])
  function toggle(id: string) { setSelected((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; if (!next.includes(primaryAssetId)) setPrimaryAssetId(next[0] || ''); return next }) }
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { await apiRequest('/api/analyses', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ requirement, assetIds: selected, primaryAssetId }) }); setRequirement(''); setSelected([]); setPrimaryAssetId(''); load() } catch { setError('分析创建失败，请检查所选数据表和需求。') } finally { setSaving(false) } }
  return <section className="stack"><h2>数据分析</h2><form className="panel stack" onSubmit={create}><h3>新建分析</h3><label>选择数据表{assets.map((asset) => <span key={asset.id}><input type="checkbox" checked={selected.includes(asset.id)} onChange={() => toggle(asset.id)} /> {asset.name}</span>)}</label>{selected.map((id) => { const preview = previews[id]; const columns = preview?.rows[0] ? Object.keys(preview.rows[0]) : []; return <div className="preview-table-wrap" key={id}><h4>{assets.find((asset) => asset.id === id)?.name} 数据参考</h4>{preview === null ? <p className="muted">正在加载预览…</p> : preview?.rows.length ? <table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{preview.rows.slice(0, 10).map((row, rowIndex) => <tr key={rowIndex}>{columns.map((column) => <td key={column}>{String(row[column] ?? '')}</td>)}</tr>)}</tbody></table> : <p className="muted">预览数据加载失败或为空。</p>}</div> })}{selected.length ? <label>主表<select value={primaryAssetId} onChange={(e) => setPrimaryAssetId(e.target.value)}>{selected.map((id) => <option key={id} value={id}>{assets.find((asset) => asset.id === id)?.name}</option>)}</select></label> : null}<label>分析需求<textarea aria-label="分析需求" required value={requirement} onChange={(e) => setRequirement(e.target.value)} placeholder="例如：按班级展示平均成绩" /></label><button disabled={saving || !primaryAssetId}>{saving ? '正在创建…' : '创建分析'}</button>{error && <p className="error">{error}</p>}</form><h2>历史分析</h2><div className="stack">{items.map((item) => <Link className="panel" key={item.id} to={`/analyses/${item.id}`}><h3>{item.title || '分析生成失败'}</h3><p>{item.requirement}</p><p className="muted">{item.assets?.map((asset) => `${asset.role === 'primary' ? '主表：' : ''}${asset.name}`).join('、')} · {item.status === 'ready' ? '可查看' : item.failureReason || '生成失败'}</p></Link>)}{!items.length && <p className="muted">还没有分析记录。</p>}</div></section> }
